name: agri-yield
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - numpy
  - pandas
  - scikit-learn
  - plotly
  - jinja2
  - joblib
  - matplotlib
  - seaborn
  - pip
  - pip:
    - python-multipart 